-- PostgreSQL schema for staging, provenance, audit, issues and unmapped data
CREATE SCHEMA IF NOT EXISTS staging;

CREATE TABLE IF NOT EXISTS staging.schema_migration (
    migration_name TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 1. ETL Run Tracking
CREATE TABLE IF NOT EXISTS staging.etl_run (
    run_id         VARCHAR(64) PRIMARY KEY,
    source_name    VARCHAR(32) NOT NULL,
    status         VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    is_dry_run     BOOLEAN NOT NULL DEFAULT FALSE,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at   TIMESTAMPTZ,
    file_checksums JSONB DEFAULT '{}'::jsonb,
    metrics        JSONB DEFAULT '{}'::jsonb,
    error_message  TEXT
);

-- 2. Snapshot Tracking
CREATE TABLE IF NOT EXISTS staging.snapshot (
    snapshot_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name       VARCHAR(32) NOT NULL,
    file_path         TEXT NOT NULL,
    file_hash         VARCHAR(64) NOT NULL,
    total_raw_records INTEGER DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- State used to prevent stale source snapshots from overwriting a newer entity.
CREATE TABLE IF NOT EXISTS staging.entity_state (
    source_name TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    source_key TEXT NOT NULL,
    snapshot_id BIGINT REFERENCES staging.snapshot(snapshot_id),
    source_observed_at TIMESTAMPTZ,
    transformer_version TEXT NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source_name, entity_type, source_key)
);

-- 3. Raw Records (JSONB payload)
CREATE TABLE IF NOT EXISTS staging.raw_record (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            VARCHAR(64) REFERENCES staging.etl_run(run_id) ON DELETE CASCADE,
    snapshot_id       BIGINT REFERENCES staging.snapshot(snapshot_id) ON DELETE SET NULL,
    source_name       VARCHAR(32) NOT NULL,
    source_entity_key TEXT,
    file_name         TEXT NOT NULL,
    sheet_name        TEXT,
    line_or_index     INTEGER,
    raw_payload       JSONB NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. ETL Issues / Quarantine / Audit
CREATE TABLE IF NOT EXISTS staging.etl_issue (
    issue_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      VARCHAR(64) REFERENCES staging.etl_run(run_id) ON DELETE CASCADE,
    source_name VARCHAR(32) NOT NULL,
    record_key  TEXT,
    field_name  TEXT,
    error_code  VARCHAR(64) NOT NULL,
    severity    VARCHAR(16) NOT NULL DEFAULT 'WARNING',
    raw_value   TEXT,
    message     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Mapping between Source Keys and NDS Primary Keys
CREATE TABLE IF NOT EXISTS staging.mapping (
    mapping_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(32) NOT NULL,
    entity_type VARCHAR(32) NOT NULL,
    source_key  TEXT NOT NULL,
    nds_id      BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_staging_mapping UNIQUE (source_name, entity_type, source_key)
);

-- 6. Unmapped / Staging-Only Data (ad prices, reference prices, policies, aggregate ratings)
CREATE TABLE IF NOT EXISTS staging.unmapped_tour_data (
    unmapped_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            VARCHAR(64) REFERENCES staging.etl_run(run_id) ON DELETE CASCADE,
    source_name       VARCHAR(32) NOT NULL,
    source_record_key TEXT NOT NULL,
    data_kind         VARCHAR(64) NOT NULL,
    payload           JSONB NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Location Aliases Dictionary
CREATE TABLE IF NOT EXISTS staging.location_alias (
    alias_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_name    TEXT NOT NULL UNIQUE,
    standard_name TEXT NOT NULL,
    location_type TEXT,
    parent_name   TEXT,
    is_verified   BOOLEAN DEFAULT TRUE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_staging_raw_record_run ON staging.raw_record(run_id);
CREATE INDEX IF NOT EXISTS idx_staging_raw_record_key ON staging.raw_record(source_name, source_entity_key);
CREATE INDEX IF NOT EXISTS idx_staging_etl_issue_run ON staging.etl_issue(run_id);
CREATE INDEX IF NOT EXISTS idx_staging_unmapped_run ON staging.unmapped_tour_data(run_id);
