-- PostgreSQL schema mapped from the provided Travel ERD
-- Relationship cardinalities are implemented with foreign keys / junction tables.

CREATE SCHEMA IF NOT EXISTS travel;
SET search_path TO travel, public;

-- ============================================================
-- 1. SourceSystem 1 ---- 0..N SourceEntity
-- ============================================================
CREATE TABLE source_system (
    source_system_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL
);

-- ============================================================
-- 2. Category 1 ---- 0..N SourceEntity
-- ============================================================
CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL
);

-- ============================================================
-- 3. SourceEntity
-- Each SourceEntity belongs to exactly one SourceSystem and Category.
-- ============================================================
CREATE TABLE source_entity (
    source_entity_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system_id  BIGINT NOT NULL,
    category_id       BIGINT NOT NULL,
    source_record_key TEXT NOT NULL,
    name              TEXT,
    description       TEXT,

    CONSTRAINT fk_source_entity_source_system
        FOREIGN KEY (source_system_id)
        REFERENCES source_system (source_system_id),

    CONSTRAINT fk_source_entity_category
        FOREIGN KEY (category_id)
        REFERENCES category (category_id)
);

-- ============================================================
-- 4. Tour subtype of SourceEntity
-- ERD has no separate tour_id: source_entity_id is inherited as PK.
-- ============================================================
CREATE TABLE tour (
    source_entity_id BIGINT PRIMARY KEY,
    duration_days    INTEGER,
    duration_nights  INTEGER,

    CONSTRAINT fk_tour_source_entity
        FOREIGN KEY (source_entity_id)
        REFERENCES source_entity (source_entity_id)
);

-- ============================================================
-- 5. Location
-- Self relationship in ERD:
-- one Location may have 0..1 parent; one parent may have 0..N children.
-- ============================================================
CREATE TABLE location (
    location_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT NOT NULL,
    location_type      TEXT,
    parent_location_id BIGINT,

    CONSTRAINT fk_location_parent
        FOREIGN KEY (parent_location_id)
        REFERENCES location (location_id)
);

-- ============================================================
-- 6. Tour M:N Location ("has destination")
-- A many-to-many relationship requires a junction table.
-- ============================================================
CREATE TABLE tour_destination (
    tour_source_entity_id BIGINT NOT NULL,
    location_id           BIGINT NOT NULL,

    PRIMARY KEY (tour_source_entity_id, location_id),

    CONSTRAINT fk_tour_destination_tour
        FOREIGN KEY (tour_source_entity_id)
        REFERENCES tour (source_entity_id),

    CONSTRAINT fk_tour_destination_location
        FOREIGN KEY (location_id)
        REFERENCES location (location_id)
);

-- ============================================================
-- 7. Tour 1 ---- 0..N TourDeparture
-- TourDeparture 0..1 ---- 1 Location ("departs from")
-- departure_location_id is nullable because the ERD allows 0..1 Location.
-- ============================================================
CREATE TABLE tour_departure (
    tour_departure_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_source_entity_id BIGINT NOT NULL,
    departure_location_id BIGINT,
    source_departure_key  TEXT,
    departure_at          TIMESTAMPTZ,

    CONSTRAINT fk_tour_departure_tour
        FOREIGN KEY (tour_source_entity_id)
        REFERENCES tour (source_entity_id),

    CONSTRAINT fk_tour_departure_location
        FOREIGN KEY (departure_location_id)
        REFERENCES location (location_id)
);

-- ============================================================
-- 8. TourDeparture 1 ---- 1..N TourDeparturePrice
-- FK guarantees every price row belongs to exactly one departure.
-- Note: a plain FK cannot enforce that every departure has at least one price.
-- ============================================================
CREATE TABLE tour_departure_price (
    tour_departure_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_departure_id       BIGINT NOT NULL,
    list_price              NUMERIC(18,2),
    sale_price              NUMERIC(18,2),
    discount_percent        NUMERIC(7,4),
    discount_amount         NUMERIC(18,2),
    currency                VARCHAR(3),
    observed_at             TIMESTAMPTZ,

    CONSTRAINT fk_tour_departure_price_departure
        FOREIGN KEY (tour_departure_id)
        REFERENCES tour_departure (tour_departure_id)
);

-- ============================================================
-- 9. Tour 1 ---- 0..N Itinerary
-- ============================================================
CREATE TABLE itinerary (
    itinerary_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_source_entity_id BIGINT NOT NULL,
    name                 TEXT,

    CONSTRAINT fk_itinerary_tour
        FOREIGN KEY (tour_source_entity_id)
        REFERENCES tour (source_entity_id)
);

-- ============================================================
-- 10. Itinerary 1 ---- 1..N ItineraryItem
-- FK guarantees each item belongs to exactly one itinerary.
-- Minimum 1 item per itinerary would require a deferred trigger/application rule.
-- ============================================================
CREATE TABLE itinerary_item (
    itinerary_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id      BIGINT NOT NULL,
    sequence_no       INTEGER,
    day_start         INTEGER,
    day_end           INTEGER,
    title             TEXT,
    description       TEXT,

    CONSTRAINT fk_itinerary_item_itinerary
        FOREIGN KEY (itinerary_id)
        REFERENCES itinerary (itinerary_id)
);

-- ============================================================
-- 11. ItineraryItem 1 ---- 0..N ItineraryStop
-- Each stop references exactly one Location.
-- ============================================================
CREATE TABLE itinerary_stop (
    itinerary_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_item_id BIGINT NOT NULL,
    location_id       BIGINT NOT NULL,
    stop_order        INTEGER,

    CONSTRAINT fk_itinerary_stop_item
        FOREIGN KEY (itinerary_item_id)
        REFERENCES itinerary_item (itinerary_item_id),

    CONSTRAINT fk_itinerary_stop_location
        FOREIGN KEY (location_id)
        REFERENCES location (location_id)
);

-- ============================================================
-- 12. SourceEntity 1 ---- 0..N Review
-- ============================================================
CREATE TABLE review (
    review_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_entity_id      BIGINT NOT NULL,
    source_review_key     TEXT,
    reviewer_display_name TEXT,
    title                 TEXT,
    content               TEXT,
    rating_value          NUMERIC(8,4),
    rating_scale          NUMERIC(8,4),
    reviewed_at           TIMESTAMPTZ,

    CONSTRAINT fk_review_source_entity
        FOREIGN KEY (source_entity_id)
        REFERENCES source_entity (source_entity_id)
);